#!/bin/sh
# freeze the screen, take a selection screenshot, and add it to the system clipboard

scrot -fs $(xdg-user-dir DOWNLOAD)'/%Y%m%d_$wx$h.png' -e 'xclip -selection clipboard -t image/png -i $f'
