#!/bin/bash

xrandr --output DisplayPort-1 --auto --left-of DisplayPort-0 --output DisplayPort-0 --mode 2560x1440 --rate 143.97 --output DisplayPort-2 --primary --auto --right-of DisplayPort-0

backg

msv restart taralli
