#!/bin/sh

usage="i     increment 5%
d     decrement 5%
0-20  set brightness directly"

if [ -f /etc/X11/xorg.conf ]; then
  b=`xrandr --verbose | grep -m 1 Brightness | cut -f2 -d ' '`
else
  b=`xrandr --verbose | grep -m 2 Brightness | tail -n1 | cut -f2 -d ' '`
fi

case $1 in
  i) b=`echo "$b + .05" | bc`; [ $b -gt 1.5 ] && b=1.5 || : ;;
  d) b=`echo "$b - .05" | bc`; [ $b -lt 0 ] && b=0 || : ;;
  [0-9]|1[0-9]|2[0-9]|30) b=`echo ".05 * $1" | bc`;;
  *) echo $usage; exit 1;;
esac

if [ -f /etc/X11/xorg.conf ]; then
  xrandr --output eDP-1 --brightness $b
  xrandr --output HDMI-1 --brightness $b &
else
  xrandr --output eDP-1-1 --brightness $b
  xrandr --output HDMI-1-1 --brightness $b &
  xrandr --output DP-0 --brightness $b &
fi
