#!/bin/sh

#export BACKGROUND="/home/tetrachromat/.dots/bg/pink_eva.jpg"
# export BACKGROUND="/home/tetrachromat/.dots/bg/red_sun.jpg"
export BACKGROUND="/home/tetrachromat/.dots/bg/tunnel.jpg"

if [ $BACKGROUND ]; then
  exec feh --bg-fill $BACKGROUND
else
  exec feh --bg-fill /home/tetrachromat/.dots/bg/alone.png
fi
