#!/bin/sh

#export BACKGROUND="/home/phat_sumo/.dots/bg/pink_eva.jpg"
# export BACKGROUND="/home/phat_sumo/.dots/bg/red_sun.jpg"
export BACKGROUND="/home/phat_sumo/.dots/bg/eva.png"

if [ $BACKGROUND ]
then
  exec feh --bg-fill $BACKGROUND
else
  exec feh --bg-fill /home/phat_sumo/.dots/bg/alone.png
fi

