#!/bin/sh
# derp - really simple xrandr brightness script
# author: phat_sumo

usage="usage: \t${0##*/}
i\tincrement 5%
d\tdecrement 5%
0-20\tset brightness directly in 5% intervals
21-30\toverset brightness, useful for very bright places
\tyou cannot overset with i or d due to xrandr limitations"

mode="p"

case "$0" in
  *aderp) mode="a";;
esac

case "$mode" in
  p) b="`xrandr --verbose | grep -m 1 Brightness | cut -f2 -d ' '`";;
  a) b="`xrandr --verbose | grep -m 2 Brightness | tail -n1 | cut -f2 -d ' '`";;
esac

case $1 in
  i) b=`echo "$b + .05" | bc`; [ 1 -eq $(echo "$b > 1" | bc) ] && b=1;;
  d) b=`echo "$b - .05" | bc`; [ 1 -eq $(echo "$b < 0" | bc) ] && b=0;;
  [0-9]|1[0-9]|2[0-9]|30) b=`echo ".05 * $1" | bc`;;
  *) echo "$usage"; exit 1;;
esac

case "$mode" in
  p) xrandr --output `xrandr | grep primary | cut -f1 -d ' '` --brightness $b;;
  a) for x in `xrandr | grep connected | grep -v disconnected | cut -f1 -d ' '`; do
       xrandr --output $x --brightness $b &
     done;;
esac
