#!/bin/bash

exec backg &
exec xrandr --output DP-0 --mode 1920x1080 --rate 144.00 --output eDP-1-1 --auto --left-of DP-0 --mode 1920x1080 --rate 120 --output HDMI-1-1 --auto --right-of DP-0 --mode 1920x1080 --rate 60 &
