#!/bin/sh

case "$1" in
  0) mode=off;;
  1) mode=low;;
  2) mode=med;;
  3) mode=high;;
  *) echo "Usage: $0 {0|1|2|3}"
     exit 1;;
esac

rog-core -d > /dev/null 2>&1 &

PID=$!

sleep 1

rog-core -b $mode > /dev/null 2>&1 &

sleep 1

kill -9 $PID

