#!/bin/sh

# launch firefox + st

sleep 1

xdotool key super+3

firefox &

sleep 4

ne &

st &

sleep 1

# resize
xdotool key super+l
xdotool key super+l

xdotool key super+8

tape &

sleep 1.5

xdotool key super+0

tidal

sleep 5

xdotool key super+9

vesktop &

telegram-desktop &

# resize
xdotool key super+l
xdotool key super+l

sleep 10

# swap pos
xdotool key super+space

xdotool key super+3
