#!/bin/sh

# launch firefox + st

sleep 1

xdotool key super+3

firefox &

st &

sleep 5.5

# swap pos
xdotool key super+space

# resize
xdotool key super+l
xdotool key super+l

# switch to left monitor
xdotool key super+comma

xdotool key super+8

tape &

sleep 1.5

xdotool key super+0
tidal &
sleep 4

xdotool key super+9

vesktop &

telegram-desktop &

# resize
xdotool key super+l
xdotool key super+l

sleep 12

# swap pos
xdotool key super+space

# switch to right monitor

xdotool key super+comma

# emacs :3
ne &

sleep 1

# swap pos
# xdotool key super+space

# back to main
xdotool key super+comma
